version: 2

models:
  - name: stg_rds_companies
    columns:
      - name: company_id
        tests:
          - unique
          - not_null
      - name: country
        tests:
          - not_null

  - name: stg_rds_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: updated_phone
        tests:
          - string_length:
              min_length: 12
              max_length: 12
