version: 2

sources:
  - name: rds
    database: northwinds
    schema: public
    tables:
      - name: customers
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
      - name: orders
        columns:
          - name: order_id
            tests:
              - not_null
      - name: order_details
        columns:
          - name: order_id
            tests:
              - not_null